function [btnPanelModel, btnPanelSensors, btnPanelGNC, separatorLine] = createPanelButtons(fig, dims)
    %CREATEPANELBUTTONS Create panel selection buttons
    
    btnWidth = dims.panelWidth / 3 - 5;
    btnHeight = dims.figHeight * 0.05;
    btnY = dims.figHeight * 0.929;
    
    btnPanelModel = uicontrol('Parent', fig, ...
                              'Style', 'pushbutton', ...
                              'String', 'MODEL', ...
                              'Position', [dims.panelX, btnY, btnWidth, btnHeight], ...
                              'FontSize', 10, ...
                              'FontWeight', 'bold', ...
                              'BackgroundColor', [0.3, 0.6, 0.9]);
    
    btnPanelSensors = uicontrol('Parent', fig, ...
                                'Style', 'pushbutton', ...
                                'String', 'SENSORS', ...
                                'Position', [dims.panelX+btnWidth+5, btnY, btnWidth, btnHeight], ...
                                'FontSize', 10, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [0.7, 0.7, 0.7]);
    
    btnPanelGNC = uicontrol('Parent', fig, ...
                            'Style', 'pushbutton', ...
                            'String', 'GNC', ...
                            'Position', [dims.panelX+2*btnWidth+10, btnY, btnWidth, btnHeight], ...
                            'FontSize', 10, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [0.7, 0.7, 0.7]);
    
    % Separator line
    separatorLine = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', '', ...
              'Position', [dims.panelX, btnY-5, dims.panelWidth, 2], ...
              'BackgroundColor', [0.3, 0.3, 0.3]);
end

function updatePanelButtons(btnModel, btnSensors, btnGNC, dims)
    %UPDATEPANELBUTTONS Update panel button positions
    
    btnWidth = dims.panelWidth / 3 - 5;
    btnHeight = dims.figHeight * 0.05;
    btnY = dims.figHeight * 0.929;
    
    set(btnModel, 'Position', [dims.panelX, btnY, btnWidth, btnHeight]);
    set(btnSensors, 'Position', [dims.panelX+btnWidth+5, btnY, btnWidth, btnHeight]);
    set(btnGNC, 'Position', [dims.panelX+2*btnWidth+10, btnY, btnWidth, btnHeight]);
end
