function [components, handles] = createModelPanel(fig, panelX, panelWidth, figHeight)
%CREATEMODELPANEL Creates the MODEL panel UI components
%
%   [components, handles] = createModelPanel(fig, panelX, panelWidth, figHeight)
%
%   Inputs:
%       fig         - Parent figure handle
%       panelX      - X position for panel
%       panelWidth  - Width of the panel
%       figHeight   - Height of the figure (for relative positioning)
%
%   Outputs:
%       components  - Array of all UI components (for visibility toggling)
%       handles     - Struct with named handles for callbacks

    handles = struct();
    
    %% Model selection buttons
    handles.txtModelLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Motion Model:', ...
              'Position', [panelX, figHeight*0.857, panelWidth*0.6, figHeight*0.036], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 10, 'FontWeight', 'bold');
    
    handles.btnDeadReckoning = uicontrol('Parent', fig, ...
                                  'Style', 'radiobutton', ...
                                  'String', 'Dead Reckoning', ...
                                  'Position', [panelX, figHeight*0.814, panelWidth*0.5, figHeight*0.036], ...
                                  'Value', 1);
    
    handles.btnOdometry = uicontrol('Parent', fig, ...
                            'Style', 'radiobutton', ...
                            'String', 'Odometry', ...
                            'Position', [panelX, figHeight*0.771, panelWidth*0.5, figHeight*0.036], ...
                            'Value', 0);
    
    %% Trajectory selection
    handles.txtTrajectoryLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Trajectory Type:', ...
              'Position', [panelX, figHeight*0.72, panelWidth*0.6, figHeight*0.036], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 10, 'FontWeight', 'bold');
    
    handles.popupTrajectory = uicontrol('Parent', fig, ...
                                'Style', 'popupmenu', ...
                                'String', {'Circular', 'Rectangle', 'Rectangle with Obstacles'}, ...
                                'Position', [panelX, figHeight*0.684, panelWidth*0.7, figHeight*0.036], ...
                                'Value', 1, ...
                                'Tag', 'popupTrajectory');
    
    %% Number of samples input
    handles.txtSamplesLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Number of Samples:', ...
              'Position', [panelX, figHeight*0.63, panelWidth*0.6, figHeight*0.036], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 10, 'FontWeight', 'bold');
    
    handles.editSamples = uicontrol('Parent', fig, ...
                            'Style', 'edit', ...
                            'String', '1000', ...
                            'Position', [panelX, figHeight*0.594, panelWidth*0.4, figHeight*0.036], ...
                            'HorizontalAlignment', 'center', ...
                            'Tag', 'editSamples');
    
    %% Alpha parameters label
    handles.txtAlphaLabel = uicontrol('Parent', fig, ...
                              'Style', 'text', ...
                              'String', 'Alpha Parameters:', ...
                              'Position', [panelX, figHeight*0.53, panelWidth*0.6, figHeight*0.036], ...
                              'HorizontalAlignment', 'left', ...
                              'FontSize', 10, 'FontWeight', 'bold');
    
    %% Create 6 sliders (show/hide based on model)
    handles.sliders = struct();
    handles.sliderLabels = struct();
    handles.sliderValues = struct();
    
    sliderSpacing = figHeight * 0.046;
    sliderHeight = figHeight * 0.029;
    
    for i = 1:6
        yPos = figHeight*0.5 - (i-1)*sliderSpacing;
        
        handles.sliderLabels.(sprintf('alpha%d', i)) = uicontrol('Parent', fig, ...
            'Style', 'text', ...
            'String', sprintf('α%d:', i), ...
            'Position', [panelX, yPos, panelWidth*0.12, sliderHeight], ...
            'HorizontalAlignment', 'left', ...
            'Tag', sprintf('sliderLabel%d', i));
        
        handles.sliders.(sprintf('alpha%d', i)) = uicontrol('Parent', fig, ...
            'Style', 'slider', ...
            'Min', 0, 'Max', 0.01, 'Value', 0.001, ...
            'Position', [panelX+panelWidth*0.14, yPos, panelWidth*0.64, sliderHeight], ...
            'Tag', sprintf('slider%d', i));
        
        handles.sliderValues.(sprintf('alpha%d', i)) = uicontrol('Parent', fig, ...
            'Style', 'text', ...
            'String', '0.001', ...
            'Position', [panelX+panelWidth*0.79, yPos, panelWidth*0.18, sliderHeight], ...
            'HorizontalAlignment', 'left', ...
            'Tag', sprintf('sliderValue%d', i));
    end
    
    %% Live simulation checkbox
    handles.chkLiveSimulation = uicontrol('Parent', fig, ...
                                  'Style', 'checkbox', ...
                                  'String', 'Live Simulation', ...
                                  'Position', [panelX, figHeight*0.15, panelWidth*0.5, figHeight*0.036], ...
                                  'Value', 0, ...
                                  'FontSize', 10);
    
    %% Pace label and input (initially hidden)
    handles.txtPaceLabel = uicontrol('Parent', fig, ...
                             'Style', 'text', ...
                             'String', 'Pace (s):', ...
                             'Position', [panelX, figHeight*0.11, panelWidth*0.3, figHeight*0.03], ...
                             'HorizontalAlignment', 'left', ...
                             'FontSize', 9, ...
                             'Visible', 'off');
    
    handles.editPace = uicontrol('Parent', fig, ...
                         'Style', 'edit', ...
                         'String', '0.1', ...
                         'Position', [panelX+panelWidth*0.32, figHeight*0.11, panelWidth*0.25, figHeight*0.03], ...
                         'HorizontalAlignment', 'center', ...
                         'FontSize', 9, ...
                         'Visible', 'off', ...
                         'Tag', 'editPace');
    
    %% Simulation control buttons
    handles.btnRun = uicontrol('Parent', fig, ...
                       'Style', 'pushbutton', ...
                       'String', 'Run', ...
                       'Position', [panelX, figHeight*0.06, panelWidth*0.22, figHeight*0.045], ...
                       'FontSize', 11, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor', [0.4, 0.7, 0.4]);
    
    handles.btnStop = uicontrol('Parent', fig, ...
                       'Style', 'pushbutton', ...
                       'String', 'Stop', ...
                       'Position', [panelX+panelWidth*0.25, figHeight*0.06, panelWidth*0.22, figHeight*0.045], ...
                       'FontSize', 11, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor', [0.9, 0.4, 0.4], ...
                       'Enable', 'off', ...
                       'Visible', 'off');
    
    handles.btnContinue = uicontrol('Parent', fig, ...
                       'Style', 'pushbutton', ...
                       'String', 'Continue', ...
                       'Position', [panelX+panelWidth*0.5, figHeight*0.06, panelWidth*0.22, figHeight*0.045], ...
                       'FontSize', 11, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor', [0.4, 0.6, 0.9], ...
                       'Enable', 'off', ...
                       'Visible', 'off');
    
    handles.btnReset = uicontrol('Parent', fig, ...
                       'Style', 'pushbutton', ...
                       'String', 'Reset', ...
                       'Position', [panelX+panelWidth*0.75, figHeight*0.06, panelWidth*0.22, figHeight*0.045], ...
                       'FontSize', 11, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor', [0.9, 0.7, 0.2], ...
                       'Enable', 'off', ...
                       'Visible', 'off');
    
    %% Save button
    handles.btnSaveResults = uicontrol('Parent', fig, ...
                       'Style', 'pushbutton', ...
                       'String', 'Save Results', ...
                       'Position', [panelX, figHeight*0.01, panelWidth*0.5, figHeight*0.04], ...
                       'FontSize', 10, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor', [0.3, 0.8, 0.8], ...
                       'Enable', 'off');
    
    %% Collect all components for visibility toggling
    sliderLabelsList = struct2cell(handles.sliderLabels);
    slidersList = struct2cell(handles.sliders);
    sliderValuesList = struct2cell(handles.sliderValues);
    
    components = [handles.txtModelLabel, handles.btnDeadReckoning, handles.btnOdometry, ...
                  handles.txtTrajectoryLabel, handles.popupTrajectory, ...
                  handles.txtSamplesLabel, handles.editSamples, handles.txtAlphaLabel, ...
                  handles.chkLiveSimulation, handles.txtPaceLabel, handles.editPace, ...
                  handles.btnRun, handles.btnStop, handles.btnContinue, handles.btnReset, handles.btnSaveResults, ...
                  sliderLabelsList{:}, slidersList{:}, sliderValuesList{:}];
end
