function [components, handles] = createGNCPanel(fig, panelX, panelWidth, figHeight)
%CREATEGNCPANEL Creates the GNC (Guidance, Navigation, Control) panel UI components
%
%   [components, handles] = createGNCPanel(fig, panelX, panelWidth, figHeight)
%
%   Inputs:
%       fig         - Parent figure handle
%       panelX      - X position for panel
%       panelWidth  - Width of the panel
%       figHeight   - Height of the figure (for relative positioning)
%
%   Outputs:
%       components  - Array of all UI components (for visibility toggling)
%       handles     - Struct with named handles for callbacks

    handles = struct();
    
    %% Title
    handles.txtTitle = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'EKF Localization', ...
              'Position', [panelX, figHeight*0.857, panelWidth*0.95, figHeight*0.043], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 12, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'gncPanelTitle');
    
    %% Estimator Selection
    handles.txtEstimatorLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'State Estimator:', ...
              'Position', [panelX, figHeight*0.81, panelWidth*0.6, figHeight*0.027], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'estimatorLabel');
    
    handles.popupEstimator = uicontrol('Parent', fig, ...
              'Style', 'popupmenu', ...
              'String', {'Extended Kalman Filter (EKF)'}, ...
              'Position', [panelX, figHeight*0.77, panelWidth*0.9, figHeight*0.036], ...
              'FontSize', 9, ...
              'Visible', 'off', ...
              'Tag', 'estimatorPopup');
    
    %% Initial Covariance Section
    handles.txtInitCovLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Initial Covariance P₀:', ...
              'Position', [panelX, figHeight*0.72, panelWidth*0.7, figHeight*0.027], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'initCovLabel');
    
    % P0_x
    handles.txtP0xLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'σ²(x):', ...
              'Position', [panelX, figHeight*0.685, panelWidth*0.25, figHeight*0.023], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'p0xLabel');
    
    handles.editP0x = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '0.1', ...
              'Position', [panelX+panelWidth*0.28, figHeight*0.685, panelWidth*0.28, figHeight*0.023], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'editP0x');
    
    % P0_y
    handles.txtP0yLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'σ²(y):', ...
              'Position', [panelX, figHeight*0.655, panelWidth*0.25, figHeight*0.023], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'p0yLabel');
    
    handles.editP0y = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '0.1', ...
              'Position', [panelX+panelWidth*0.28, figHeight*0.655, panelWidth*0.28, figHeight*0.023], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'editP0y');
    
    % P0_theta
    handles.txtP0thetaLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'σ²(θ):', ...
              'Position', [panelX, figHeight*0.625, panelWidth*0.25, figHeight*0.023], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'p0thetaLabel');
    
    handles.editP0theta = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '0.05', ...
              'Position', [panelX+panelWidth*0.28, figHeight*0.625, panelWidth*0.28, figHeight*0.023], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'editP0theta');
    
    %% Sensor Parameters (from SENSORS panel)
    handles.txtSensorParamsLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Sensor & Measurement Config:', ...
              'Position', [panelX, figHeight*0.58, panelWidth*0.8, figHeight*0.027], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'sensorParamsLabel');
    
    handles.txtSensorInfo = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Range/bearing noise from SENSORS panel', ...
              'Position', [panelX, figHeight*0.545, panelWidth*0.9, figHeight*0.023], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'ForegroundColor', [0.4, 0.4, 0.4], ...
              'Visible', 'off', ...
              'Tag', 'sensorInfo');
    
    %% Landmark Radius
    handles.txtLandmarkRadiusLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Landmark Radius (m):', ...
              'Position', [panelX, figHeight*0.51, panelWidth*0.5, figHeight*0.023], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'landmarkRadiusLabel');
    
    handles.editLandmarkRadius = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '0.05', ...
              'Position', [panelX+panelWidth*0.55, figHeight*0.51, panelWidth*0.28, figHeight*0.023], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'editLandmarkRadius');
    
    %% Separator Line 1
    handles.separator1 = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', '', ...
              'Position', [panelX, figHeight*0.48, panelWidth, 2], ...
              'BackgroundColor', [0.3, 0.3, 0.3], ...
              'Visible', 'off', ...
              'Tag', 'gncSeparator1');
    
    %% Visualization Options
    handles.txtVisLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Visualization:', ...
              'Position', [panelX, figHeight*0.34, panelWidth*0.6, figHeight*0.027], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'visLabel');
    
    handles.chkShowEstimate = uicontrol('Parent', fig, ...
              'Style', 'checkbox', ...
              'String', 'Show EKF Estimate', ...
              'Value', 1, ...
              'Position', [panelX, figHeight*0.31, panelWidth*0.7, figHeight*0.025], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'chkShowEstimate');
    
    handles.chkShowEllipsoid = uicontrol('Parent', fig, ...
              'Style', 'checkbox', ...
              'String', 'Show Uncertainty Ellipsoid', ...
              'Value', 1, ...
              'Position', [panelX, figHeight*0.28, panelWidth*0.8, figHeight*0.025], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'chkShowEllipsoid');
    
    handles.chkShowDetections = uicontrol('Parent', fig, ...
              'Style', 'checkbox', ...
              'String', 'Show Landmark Detections', ...
              'Value', 1, ...
              'Position', [panelX, figHeight*0.25, panelWidth*0.8, figHeight*0.025], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'chkShowDetections');
    
    %% Ellipsoid Confidence Level
    handles.txtConfidenceLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Confidence (σ):', ...
              'Position', [panelX, figHeight*0.215, panelWidth*0.4, figHeight*0.023], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'confidenceLabel');
    
    handles.editConfidence = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '3', ...
              'Position', [panelX+panelWidth*0.45, figHeight*0.215, panelWidth*0.2, figHeight*0.023], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'editConfidence');
    
    handles.txtConfidenceInfo = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', '(1σ=68%, 2σ=95%, 3σ=99.7%)', ...
              'Position', [panelX, figHeight*0.19, panelWidth*0.9, figHeight*0.020], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 7, ...
              'ForegroundColor', [0.4, 0.4, 0.4], ...
              'Visible', 'off', ...
              'Tag', 'confidenceInfo');
    
    %% Separator
    handles.separator2 = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', '', ...
              'Position', [panelX, figHeight*0.165, panelWidth, 2], ...
              'BackgroundColor', [0.3, 0.3, 0.3], ...
              'Visible', 'off', ...
              'Tag', 'gncSeparator2');
    
    %% Control Buttons
    handles.btnRunEKF = uicontrol('Parent', fig, ...
              'Style', 'pushbutton', ...
              'String', 'Run EKF', ...
              'Position', [panelX, figHeight*0.12, panelWidth*0.45, figHeight*0.04], ...
              'FontSize', 9, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.2, 0.7, 0.3], ...
              'Visible', 'off', ...
              'Tag', 'btnRunEKF');
    
    handles.btnResetEKF = uicontrol('Parent', fig, ...
              'Style', 'pushbutton', ...
              'String', 'Reset', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.12, panelWidth*0.45, figHeight*0.04], ...
              'FontSize', 9, ...
              'Visible', 'off', ...
              'Tag', 'btnResetEKF');
    
    %% Live Update Checkbox
    handles.chkLiveEKF = uicontrol('Parent', fig, ...
              'Style', 'checkbox', ...
              'String', 'Live Update', ...
              'Value', 1, ...
              'Position', [panelX, figHeight*0.08, panelWidth*0.5, figHeight*0.025], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'chkLiveEKF');
    
    handles.txtPaceLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Pace (s):', ...
              'Position', [panelX, figHeight*0.05, panelWidth*0.3, figHeight*0.023], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'ekfPaceLabel');
    
    handles.editPace = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '0.1', ...
              'Position', [panelX+panelWidth*0.32, figHeight*0.05, panelWidth*0.25, figHeight*0.023], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'editEKFPace');
    
    %% Status Display
    handles.txtStatus = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Status: Ready', ...
              'Position', [panelX, figHeight*0.01, panelWidth*0.95, figHeight*0.035], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'ForegroundColor', [0, 0.5, 0], ...
              'Visible', 'off', ...
              'Tag', 'gncStatus');
    
    %% Collect all components for visibility toggling
    components = [handles.txtTitle, handles.txtEstimatorLabel, handles.popupEstimator, ...
                  handles.txtInitCovLabel, handles.txtP0xLabel, handles.editP0x, ...
                  handles.txtP0yLabel, handles.editP0y, handles.txtP0thetaLabel, handles.editP0theta, ...
                  handles.txtSensorParamsLabel, handles.txtSensorInfo, ...
                  handles.txtLandmarkRadiusLabel, handles.editLandmarkRadius, ...
                  handles.separator1, handles.txtVisLabel, ...
                  handles.chkShowEstimate, handles.chkShowEllipsoid, handles.chkShowDetections, ...
                  handles.txtConfidenceLabel, handles.editConfidence, handles.txtConfidenceInfo, ...
                  handles.separator2, handles.btnRunEKF, handles.btnResetEKF, ...
                  handles.chkLiveEKF, handles.txtPaceLabel, handles.editPace, handles.txtStatus];
end
