function [components, handles] = createSensorsPanel(fig, panelX, panelWidth, figHeight)
%CREATESENSORSPANEL Creates the SENSORS panel UI components for 2D Lidar
%
%   [components, handles] = createSensorsPanel(fig, panelX, panelWidth, figHeight)
%
%   Inputs:
%       fig         - Parent figure handle
%       panelX      - X position for panel
%       panelWidth  - Width of the panel
%       figHeight   - Height of the figure (for relative positioning)
%
%   Outputs:
%       components  - Array of all UI components (for visibility toggling)
%       handles     - Struct with named handles for callbacks

    handles = struct();
    
    %% Title
    handles.txtTitle = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Sensors & Landmarks', ...
              'Position', [panelX, figHeight*0.857, panelWidth*0.95, figHeight*0.043], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 11, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'sensorsPanelTitle');
    
    %% Lidar Parameters Section
    handles.txtLidarParams = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Lidar Parameters:', ...
              'Position', [panelX, figHeight*0.81, panelWidth*0.6, figHeight*0.027], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'lidarParamsLabel');
    
    %% Separator line after lidar section
    handles.separatorLidar = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', '', ...
              'Position', [panelX, figHeight*0.425, panelWidth, 2], ...
              'BackgroundColor', [0.5, 0.5, 0.5], ...
              'Visible', 'off', ...
              'Tag', 'lidarSeparator');
    
    %% Range (Distance) Parameter
    handles.txtRangeLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Max Range (m):', ...
              'Position', [panelX, figHeight*0.775, panelWidth*0.45, figHeight*0.025], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarRangeLabel');
    
    handles.editRange = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '10', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.775, panelWidth*0.35, figHeight*0.025], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarRange');
    
    %% Field of View Parameter
    handles.txtFOVLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Field of View (°):', ...
              'Position', [panelX, figHeight*0.74, panelWidth*0.45, figHeight*0.025], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarFOVLabel');
    
    handles.editFOV = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '90', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.74, panelWidth*0.35, figHeight*0.025], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarFOV');
    
    %% Resolution Parameter
    handles.txtResLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Resolution (°):', ...
              'Position', [panelX, figHeight*0.705, panelWidth*0.45, figHeight*0.025], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarResolutionLabel');
    
    handles.editResolution = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '2', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.705, panelWidth*0.35, figHeight*0.025], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarResolution');
    
    %% Lidar Info Display
    handles.txtInfoLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Scan Info:', ...
              'Position', [panelX, figHeight*0.665, panelWidth*0.4, figHeight*0.027], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'lidarScanInfoLabel');
    
    handles.txtNumRays = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Rays: 91', ...
              'Position', [panelX, figHeight*0.635, panelWidth*0.5, figHeight*0.025], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'numRaysDisplay');
    
    handles.txtAngleRange = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Angles: -90° to 90°', ...
              'Position', [panelX, figHeight*0.61, panelWidth*0.8, figHeight*0.025], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'angleRangeDisplay');
    
    %% Noise Parameters Section
    handles.txtNoiseLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Noise:', ...
              'Position', [panelX, figHeight*0.58, panelWidth*0.6, figHeight*0.023], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'lidarNoiseLabel');
    
    % Range noise (standard deviation)
    handles.txtRangeNoiseLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Range σ (m):', ...
              'Position', [panelX, figHeight*0.555, panelWidth*0.45, figHeight*0.020], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarRangeNoiseLabel');
    
    handles.editRangeNoise = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '0.1', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.555, panelWidth*0.35, figHeight*0.020], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarRangeNoise');
    
    % Angular noise (standard deviation)
    handles.txtAngularNoiseLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Angular σ (°):', ...
              'Position', [panelX, figHeight*0.530, panelWidth*0.45, figHeight*0.020], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarAngularNoiseLabel');
    
    handles.editAngularNoise = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '0.5', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.530, panelWidth*0.35, figHeight*0.020], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'lidarAngularNoise');
    
    %% Visualization Options
    handles.chkShowLidar = uicontrol('Parent', fig, ...
              'Style', 'checkbox', ...
              'String', 'Show Lidar Rays', ...
              'Position', [panelX, figHeight*0.50, panelWidth*0.6, figHeight*0.025], ...
              'Value', 1, ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'showLidarRays');
    
    handles.chkShowNoisyRays = uicontrol('Parent', fig, ...
              'Style', 'checkbox', ...
              'String', 'Show Noisy Readings', ...
              'Position', [panelX, figHeight*0.47, panelWidth*0.6, figHeight*0.025], ...
              'Value', 0, ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'showNoisyRays');
    
    %% Lidar Control Buttons
    handles.btnCreateScan = uicontrol('Parent', fig, ...
              'Style', 'pushbutton', ...
              'String', 'Create Scan', ...
              'Position', [panelX, figHeight*0.44, panelWidth*0.45, figHeight*0.025], ...
              'FontSize', 8, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.4, 0.7, 0.4], ...
              'Visible', 'off', ...
              'Tag', 'btnCreateScan');
    
    handles.btnClearScan = uicontrol('Parent', fig, ...
              'Style', 'pushbutton', ...
              'String', 'Clear Scan', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.44, panelWidth*0.45, figHeight*0.025], ...
              'FontSize', 8, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.9, 0.5, 0.5], ...
              'Visible', 'off', ...
              'Tag', 'btnClearScan');
    
    %% Landmarks Section
    handles.txtLandmarksTitle = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Landmarks:', ...
              'Position', [panelX, figHeight*0.38, panelWidth*0.3, figHeight*0.025], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 10, 'FontWeight', 'bold', ...
              'Visible', 'off', ...
              'Tag', 'landmarksTitle');
    
    %% Landmark List
    handles.listLandmarks = uicontrol('Parent', fig, ...
              'Style', 'listbox', ...
              'String', {}, ...
              'Position', [panelX, figHeight*0.24, panelWidth*0.95, figHeight*0.15], ...
              'FontSize', 8, ...
              'Visible', 'off', ...
              'Tag', 'listLandmarks');
    
    %% Manual Entry Section
    handles.txtManualEntry = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Add Manually:', ...
              'Position', [panelX, figHeight*0.20, panelWidth*0.5, figHeight*0.025], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, ...
              'Visible', 'off', ...
              'Tag', 'landmarkManualEntryLabel');
    
    handles.txtXLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'X:', ...
              'Position', [panelX, figHeight*0.165, panelWidth*0.1, figHeight*0.025], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, ...
              'Visible', 'off', ...
              'Tag', 'landmarkXLabel');
    
    handles.editLandmarkX = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '0', ...
              'Position', [panelX+panelWidth*0.12, figHeight*0.165, panelWidth*0.35, figHeight*0.025], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 9, ...
              'Visible', 'off', ...
              'Tag', 'editLandmarkX');
    
    handles.txtYLabel = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Y:', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.165, panelWidth*0.1, figHeight*0.025], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, ...
              'Visible', 'off', ...
              'Tag', 'landmarkYLabel');
    
    handles.editLandmarkY = uicontrol('Parent', fig, ...
              'Style', 'edit', ...
              'String', '0', ...
              'Position', [panelX+panelWidth*0.62, figHeight*0.165, panelWidth*0.35, figHeight*0.025], ...
              'HorizontalAlignment', 'center', ...
              'FontSize', 9, ...
              'Visible', 'off', ...
              'Tag', 'editLandmarkY');
    
    %% Landmark Control Buttons
    handles.btnAddManual = uicontrol('Parent', fig, ...
              'Style', 'pushbutton', ...
              'String', 'Add Manual', ...
              'Position', [panelX, figHeight*0.125, panelWidth*0.45, figHeight*0.035], ...
              'FontSize', 8, ...
              'BackgroundColor', [0.6, 0.8, 0.6], ...
              'Visible', 'off', ...
              'Tag', 'btnAddManual');
    
    handles.btnAddByClick = uicontrol('Parent', fig, ...
              'Style', 'pushbutton', ...
              'String', 'Add by Click', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.125, panelWidth*0.45, figHeight*0.035], ...
              'FontSize', 8, ...
              'BackgroundColor', [0.7, 0.7, 0.9], ...
              'Visible', 'off', ...
              'Tag', 'btnAddByClick');
    
    handles.btnRemoveLandmark = uicontrol('Parent', fig, ...
              'Style', 'pushbutton', ...
              'String', 'Remove Selected', ...
              'Position', [panelX, figHeight*0.085, panelWidth*0.45, figHeight*0.035], ...
              'FontSize', 8, ...
              'BackgroundColor', [0.9, 0.7, 0.5], ...
              'Visible', 'off', ...
              'Tag', 'btnRemoveLandmark');
    
    handles.btnClearLandmarks = uicontrol('Parent', fig, ...
              'Style', 'pushbutton', ...
              'String', 'Clear All', ...
              'Position', [panelX+panelWidth*0.5, figHeight*0.085, panelWidth*0.45, figHeight*0.035], ...
              'FontSize', 8, ...
              'BackgroundColor', [0.9, 0.5, 0.5], ...
              'Visible', 'off', ...
              'Tag', 'btnClearLandmarks');
    
    %% Status Display
    handles.txtStatus = uicontrol('Parent', fig, ...
              'Style', 'text', ...
              'String', 'Status: Ready', ...
              'Position', [panelX, figHeight*0.04, panelWidth*0.95, figHeight*0.035], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, ...
              'ForegroundColor', [0, 0.5, 0], ...
              'Visible', 'off', ...
              'Tag', 'sensorStatus');
    
    %% Collect all components for visibility toggling
    components = [handles.txtTitle, handles.txtLidarParams, ...
                  handles.txtRangeLabel, handles.editRange, ...
                  handles.txtFOVLabel, handles.editFOV, ...
                  handles.txtResLabel, handles.editResolution, ...
                  handles.txtInfoLabel, handles.txtNumRays, handles.txtAngleRange, ...
                  handles.txtNoiseLabel, ...
                  handles.txtRangeNoiseLabel, handles.editRangeNoise, ...
                  handles.txtAngularNoiseLabel, handles.editAngularNoise, ...
                  handles.chkShowLidar, handles.chkShowNoisyRays, ...
                  handles.separatorLidar, handles.btnCreateScan, handles.btnClearScan, ...
                  handles.txtLandmarksTitle, handles.listLandmarks, ...
                  handles.txtManualEntry, handles.txtXLabel, handles.editLandmarkX, ...
                  handles.txtYLabel, handles.editLandmarkY, ...
                  handles.btnAddManual, handles.btnAddByClick, ...
                  handles.btnRemoveLandmark, handles.btnClearLandmarks, ...
                  handles.txtStatus];
end
